apiVersion: v1
kind: Pod
metadata:
  name: lanchonete-api
  labels:
    app: lanchonete-api
spec:
  containers:
    - name: lanchonete-api
      image: gtbarbosa/fiap-tech-challenge-lanchonete:latest
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://192.168.49.2:3306/lanchonete
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass